// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace MyCookbook.Data.CookbookDatabase
{
    [PrimaryKey("UserName", "RecipeId")]
    public partial class FavoriteRecipe
    {
        public string UserName { get; set; }
        public int RecipeId { get; set; }

        public virtual Recipe Recipe { get; set; }
    }
}