// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace MyCookbook.Data.CookbookDatabase
{
    public partial class Ingredient
    {
        public int Id { get; set; }
        public int RecipeId { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Amount { get; set; }
        public int Order { get; set; }

        public virtual Recipe Recipe { get; set; }

        public Ingredient Clone(Recipe recipe)
        {
            return new Ingredient()
            {
                RecipeId = recipe.Id,
                UserName = recipe.UserName,
                Name = Name,
                Amount = Amount,
                Order = Order
            };
        }
    }
}