// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyCookbook.Data.CookbookDatabase
{
    public partial class Ingredient
    {
        public int Id { get; set; }
        public int RecipeId { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public double? Amount { get; set; }
        public string Unit { get; set; }
        public int Order { get; set; }

        public virtual Recipe Recipe { get; set; }
    }
}