// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyCookbook.Data.CookbookDatabase
{
    public partial class Recipe
    {
        public Recipe()
        {
            Ingredients = new HashSet<Ingredient>();
            Steps = new HashSet<Step>();
        }

        public int Id { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public int? Duration { get; set; }
        public int Servings { get; set; }
        public DateTime? LastCooked { get; set; }

        public virtual ICollection<Ingredient> Ingredients { get; set; }
        public virtual ICollection<Step> Steps { get; set; }

        [NotMapped]
        public string DurationText
        {
            get
            {
                if (Duration == null) return "";

                var span = TimeSpan.FromMinutes(Duration ?? 0);
                return span.Hours > 0 ? $"{span.Hours}:{span.Minutes}" : span.Minutes.ToString();
            }

            set
            {
                Duration = TimeSpan.TryParse(value, out var span) ? (int)Math.Round(span.TotalMinutes) : null;
            }
        }
    }
}