// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations.Schema;

namespace MyCookbook.Data.CookbookDatabase
{
    public partial class Recipe
    {
        public Recipe()
        {
            Ingredients = new HashSet<Ingredient>();
            Steps = new HashSet<Step>();
        }

        public int Id { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public int? Duration { get; set; }
        public int? ActiveDuration { get; set; }
        public int Servings { get; set; }
        public DateTime? LastCooked { get; set; }

        public virtual ICollection<Ingredient> Ingredients { get; set; }
        public virtual ICollection<Step> Steps { get; set; }

        [NotMapped]
        public string DurationText
        {
            get
            {
                if (Duration == null) return "";

                var span = TimeSpan.FromMinutes(Duration ?? 0);
                return $"{Math.Floor(span.TotalHours)}:{span.Minutes}";
            }

            set
            {
                Duration = int.TryParse(value, out var minutes) ? minutes : (int)TimeSpan.Parse(value).TotalMinutes;
            }
        }

        [NotMapped]
        public string ActiveDurationText
        {
            get
            {
                if (ActiveDuration == null) return "";

                var span = TimeSpan.FromMinutes(ActiveDuration ?? 0);
                return $"{Math.Floor(span.TotalHours)}:{span.Minutes}";
            }

            set
            {
                ActiveDuration = int.TryParse(value, out var minutes) ? minutes : (int)TimeSpan.Parse(value).TotalMinutes;
            }
        }
    }
}