// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace MyCookbook.Data.CookbookDatabase
{
    public partial class Step
    {
        public int Id { get; set; }
        public int RecipeId { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public int Order { get; set; }

        public virtual Recipe Recipe { get; set; }

        public Step Clone(Recipe recipe)
        {
            return new Step()
            {
                RecipeId = recipe.Id,
                UserName = recipe.UserName,
                Description = Description,
                Order = Order
            };
        }
    }
}