// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace MyCookbook.Data.CookbookDatabase
{
    [PrimaryKey("UserName", "RecipeId", "Name")]
    public partial class Tag // TODO: this should be a Recipe table column instead
    {
        public string UserName { get; set; }
        public int RecipeId { get; set; }
        public string Name { get; set; }

        public virtual Recipe Recipe { get; set; }

        public Tag Clone(Recipe recipe)
        {
            return new Tag()
            {
                RecipeId = recipe.Id,
                UserName = recipe.UserName,
                Name = recipe.Name
            };
        }
    }
}