// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using Microsoft.EntityFrameworkCore;

namespace MyCookbook.Data.CookbookDatabase
{
    [PrimaryKey("UserName", "Key")]
    public partial class UserPreference
    {
        public string UserName { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
    }
}